This script creates a linear model, second degree polynomial model, and third degree polynomial model. It then generates Mean Squared Error and R2 scores and stores the results in a new dataframe to export for performance comparison as a csv file. Also creates dataframes for each model stemming from evaluating the model with the true values for GDP Growth and CCI for visual model evaluation later.

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Data Importing and Feature Separation

In [2]:
#Importing economic data
folderpath = 'C:\\Users\\micha\\Desktop\\File References\\CIS480\\Project\\Data\\'
data = pd.read_csv(folderpath + 'Data.csv')

data.head()

,observation,PCE,PCEDG,PCES,PCEF,GDP_Growth,CCI
0,"Saturday, January 1, 2022",17106.0,2066.9,11299.1,1352.0,-1.0,113.8
1,"Tuesday, February 1, 2022",17347.2,2084.5,11426.5,1361.0,-1.0,110.5
2,"Tuesday, March 1, 2022",17490.0,2118.0,11537.2,1372.0,-1.0,107.2
3,"Friday, April 1, 2022",17574.5,2062.6,11619.1,1385.8,0.6,107.3
4,"Sunday, May 1, 2022",17755.2,2068.5,11721.1,1404.1,0.6,106.4

In [3]:
#Seperating features and targets
X_model_test = data[['GDP_Growth', 'CCI']]
X_gdp = data[['GDP_Growth']]
X_cci = data[['CCI']]
y = data[['PCE', 'PCEDG', 'PCES', 'PCEF']]

# Testing Each Model Type for Effectiveness

In [4]:
#Creating second degree polynomial model
poly_two = PolynomialFeatures(degree=2, include_bias=False)
X_poly_two = poly_two.fit_transform(X_model_test)

X_train, X_test, y_train, y_test = train_test_split(X_poly_two, y, test_size=.3, random_state=42)

model_poly_two = LinearRegression()
model_poly_two.fit(X_train, y_train)

y_pred_poly_two = model_poly_two.predict(X_test)

In [5]:
#Evaluating second degree polynomial model
y_test_np = y_test.to_numpy()

poly_two_pce_rmse = mean_squared_error(y_test_np[:, 0], y_pred_poly_two[:, 0], squared=False)
poly_two_pcedg_rmse = mean_squared_error(y_test_np[:, 1], y_pred_poly_two[:, 1], squared=False)
poly_two_pces_rmse = mean_squared_error(y_test_np[:, 2], y_pred_poly_two[:, 2], squared=False)
poly_two_pcef_rmse = mean_squared_error(y_test_np[:, 3], y_pred_poly_two[:, 3], squared=False)
poly_two_pce_r_squared = r2_score(y_test_np[:, 0], y_pred_poly_two[:, 0])
poly_two_pcedg_r_squared = r2_score(y_test_np[:, 1], y_pred_poly_two[:, 1])
poly_two_pces_r_squared = r2_score(y_test_np[:, 2], y_pred_poly_two[:, 2])
poly_two_pcef_r_squared = r2_score(y_test_np[:, 3], y_pred_poly_two[:, 3])
poly_two_pce_mae = mean_absolute_error(y_test_np[:, 0], y_pred_poly_two[:, 0])
poly_two_pcedg_mae = mean_absolute_error(y_test_np[:, 1], y_pred_poly_two[:, 1])
poly_two_pces_mae = mean_absolute_error(y_test_np[:, 2], y_pred_poly_two[:, 2])
poly_two_pcef_mae = mean_absolute_error(y_test_np[:, 3], y_pred_poly_two[:, 3])

C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [6]:
#Creating third degree polynomial model
poly_three = PolynomialFeatures(degree=3, include_bias=False)
X_poly_three = poly_three.fit_transform(X_model_test)

X_train, X_test, y_train, y_test = train_test_split(X_poly_three, y, test_size=.3, random_state=42)

model_poly_three = LinearRegression()
model_poly_three.fit(X_train, y_train)

y_pred_poly_three = model_poly_three.predict(X_test)

In [7]:
#Evaluating third degree polynomial model
poly_three_pce_rmse = mean_squared_error(y_test_np[:, 0], y_pred_poly_three[:, 0], squared=False)
poly_three_pcedg_rmse = mean_squared_error(y_test_np[:, 1], y_pred_poly_three[:, 1], squared=False)
poly_three_pces_rmse = mean_squared_error(y_test_np[:, 2], y_pred_poly_three[:, 2], squared=False)
poly_three_pcef_rmse = mean_squared_error(y_test_np[:, 3], y_pred_poly_three[:, 3], squared=False)
poly_three_pce_r_squared = r2_score(y_test_np[:, 0], y_pred_poly_three[:, 0])
poly_three_pcedg_r_squared = r2_score(y_test_np[:, 1], y_pred_poly_three[:, 1])
poly_three_pces_r_squared = r2_score(y_test_np[:, 2], y_pred_poly_three[:, 2])
poly_three_pcef_r_squared = r2_score(y_test_np[:, 3], y_pred_poly_three[:, 3])
poly_three_pce_mae = mean_absolute_error(y_test_np[:, 0], y_pred_poly_three[:, 0])
poly_three_pcedg_mae = mean_absolute_error(y_test_np[:, 1], y_pred_poly_three[:, 1])
poly_three_pces_mae = mean_absolute_error(y_test_np[:, 2], y_pred_poly_three[:, 2])
poly_three_pcef_mae = mean_absolute_error(y_test_np[:, 3], y_pred_poly_three[:, 3])

C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [8]:
#Creating linear model
X_train, X_test, y_train, y_test = train_test_split(X_model_test, y, test_size=.3, random_state=42)

model_linear = LinearRegression()
model_linear.fit(X_train, y_train)

y_pred_linear = model_linear.predict(X_test)

In [9]:
#Evaluating linear model
linear_pce_rmse = mean_squared_error(y_test_np[:, 0], y_pred_linear[:, 0], squared=False)
linear_pcedg_rmse = mean_squared_error(y_test_np[:, 1], y_pred_linear[:, 1], squared=False)
linear_pces_rmse = mean_squared_error(y_test_np[:, 2], y_pred_linear[:, 2], squared=False)
linear_pcef_rmse = mean_squared_error(y_test_np[:, 3], y_pred_linear[:, 3], squared=False)
linear_pce_r_squared = r2_score(y_test_np[:, 0], y_pred_linear[:, 0])
linear_pcedg_r_squared = r2_score(y_test_np[:, 1], y_pred_linear[:, 1])
linear_pces_r_squared = r2_score(y_test_np[:, 2], y_pred_linear[:, 2])
linear_pcef_r_squared = r2_score(y_test_np[:, 3], y_pred_linear[:, 3])
linear_pce_mae = mean_absolute_error(y_test_np[:, 0], y_pred_linear[:, 0])
linear_pcedg_mae = mean_absolute_error(y_test_np[:, 1], y_pred_linear[:, 1])
linear_pces_mae = mean_absolute_error(y_test_np[:, 2], y_pred_linear[:, 2])
linear_pcef_mae = mean_absolute_error(y_test_np[:, 3], y_pred_linear[:, 3])

C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [10]:
#Creating dataframe for evaluation metrics and exporting it as a csv file
model_evaluation_table = pd.DataFrame(
                        {
                        'Model_Type': ['Linear', 'Second Degree Polynomial', 'Third Degree Polynomial'],
                        'PCE_RMSE': [linear_pce_rmse, poly_two_pce_rmse, poly_three_pce_rmse],
                        'PCEDG_RMSE': [linear_pcedg_rmse, poly_two_pcedg_rmse, poly_three_pcedg_rmse],
                        'PCES_RMSE': [linear_pces_rmse, poly_two_pces_rmse, poly_three_pces_rmse],
                        'PCEF_RMSE': [linear_pcef_rmse, poly_two_pcef_rmse, poly_three_pcef_rmse],
                        'PCE_R-Squared': [linear_pce_r_squared, poly_two_pce_r_squared, poly_three_pce_r_squared],
                        'PCEDG_R-Squared': [linear_pcedg_r_squared, poly_two_pcedg_r_squared, poly_three_pcedg_r_squared],
                        'PCES_R-Squared': [linear_pces_r_squared, poly_two_pces_r_squared, poly_three_pces_r_squared],
                        'PCEF_R-Squared': [linear_pcef_r_squared, poly_two_pcef_r_squared, poly_three_pcef_r_squared],
                        'PCE_MAE': [linear_pce_mae, poly_two_pce_mae, poly_three_pce_mae],
                        'PCEDG_MAE': [linear_pcedg_mae, poly_two_pcedg_mae, poly_three_pcedg_mae],
                        'PCES_MAE': [linear_pces_mae, poly_two_pces_mae, poly_three_pces_mae],
                        'PCEF_MAE': [linear_pcef_mae, poly_two_pcef_mae, poly_three_pcef_mae]
                        }
)

model_evaluation_table.head()

,Model_Type,PCE_RMSE,PCEDG_RMSE,PCES_RMSE,PCEF_RMSE,PCE_R-Squared,PCEDG_R-Squared,PCES_R-Squared,PCEF_R-Squared,PCE_MAE,PCEDG_MAE,PCES_MAE,PCEF_MAE
0,Linear,1139.098362,63.865648,970.463099,45.522678,0.064559,0.242671,0.043762,0.034875,998.814823,50.606607,853.572413,39.363139
1,Second Degree Polynomial,1236.393772,74.099757,1040.309085,48.986986,-0.102066,-0.019492,-0.098836,-0.117608,1072.250260,57.486184,912.211361,41.846802
2,Third Degree Polynomial,1313.953733,92.124620,1079.431430,53.823469,-0.244670,-0.575802,-0.183036,-0.349185,985.752703,72.594746,823.797574,38.595387

In [11]:
model_evaluation_table.to_csv(folderpath + 'Model_Evaluation_Table.csv')

The linear model appears to be the most accurate model for predicting consumer spending based on the evaluation metrics: RMSE, MAE, and R-Squared.

# Modeling GDP_Growth as a Predictor

In [12]:
#Creating linear model for GDP_Growth
X_train, X_test, y_train, y_test = train_test_split(X_gdp, y, test_size=.3, random_state=42)

model_linear_gdp_growth = LinearRegression()
model_linear_gdp_growth.fit(X_train, y_train)

y_pred_linear_gdp_growth = model_linear_gdp_growth.predict(X_test)

In [13]:
#Evaluating linear model for GDP_Growth
gdp_growth_pce_rmse = mean_squared_error(y_test_np[:, 0], y_pred_linear_gdp_growth[:, 0], squared=False)
gdp_growth_pcedg_rmse = mean_squared_error(y_test_np[:, 1], y_pred_linear_gdp_growth[:, 1], squared=False)
gdp_growth_pces_rmse = mean_squared_error(y_test_np[:, 2], y_pred_linear_gdp_growth[:, 2], squared=False)
gdp_growth_pcef_rmse = mean_squared_error(y_test_np[:, 3], y_pred_linear_gdp_growth[:, 3], squared=False)
gdp_growth_pce_r_squared = r2_score(y_test_np[:, 0], y_pred_linear_gdp_growth[:, 0])
gdp_growth_pcedg_r_squared = r2_score(y_test_np[:, 1], y_pred_linear_gdp_growth[:, 1])
gdp_growth_pces_r_squared = r2_score(y_test_np[:, 2], y_pred_linear_gdp_growth[:, 2])
gdp_growth_pcef_r_squared = r2_score(y_test_np[:, 3], y_pred_linear_gdp_growth[:, 3])
gdp_growth_pce_mae = mean_absolute_error(y_test_np[:, 0], y_pred_linear_gdp_growth[:, 0])
gdp_growth_pcedg_mae = mean_absolute_error(y_test_np[:, 1], y_pred_linear_gdp_growth[:, 1])
gdp_growth_pces_mae = mean_absolute_error(y_test_np[:, 2], y_pred_linear_gdp_growth[:, 2])
gdp_growth_pcef_mae = mean_absolute_error(y_test_np[:, 3], y_pred_linear_gdp_growth[:, 3])

C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [14]:
#Creating dataframe consisting of the predicted values by the linear model for GDP Growth given each true observation of GDP Growth and CCI and exporting it as a csv for later comparison
counter = 0
gdp_growth_predictions_true_values = pd.DataFrame(
    {
        'observation':[],
        'PCE_Pred':[],
        'PCEDG_Pred':[],
        'PCES_Pred':[],
        'PCEF_Pred':[],
        'GDP_Growth':[]
    }
)

for observation in data['observation']:
    prediction_df = pd.DataFrame([[data['GDP_Growth'][counter]]], columns = ['GDP_Growth'])
    prediction = model_linear_gdp_growth.predict(prediction_df)
    gdp_growth_predictions_true_values.loc[len(gdp_growth_predictions_true_values)] = [data['observation'][counter],
                                                                                           prediction[0][0],
                                                                                           prediction[0][1],
                                                                                           prediction[0][2],
                                                                                           prediction[0][3],
                                                                                           data['GDP_Growth'][counter]]
    counter = counter + 1

gdp_growth_predictions_true_values.to_csv(folderpath + 'GDP_Growth_Predictions_True_Values.csv')

# Modeling CCI as a Predictor

In [15]:
#Creating linear model for CCI
X_train, X_test, y_train, y_test = train_test_split(X_cci, y, test_size=.3, random_state=42)

model_linear_cci = LinearRegression()
model_linear_cci.fit(X_train, y_train)

y_pred_linear_cci = model_linear_cci.predict(X_test)

In [16]:
#Evaluating linear model for CCI
cci_pce_rmse = mean_squared_error(y_test_np[:, 0], y_pred_linear_cci[:, 0], squared=False)
cci_pcedg_rmse = mean_squared_error(y_test_np[:, 1], y_pred_linear_cci[:, 1], squared=False)
cci_pces_rmse = mean_squared_error(y_test_np[:, 2], y_pred_linear_cci[:, 2], squared=False)
cci_pcef_rmse = mean_squared_error(y_test_np[:, 3], y_pred_linear_cci[:, 3], squared=False)
cci_pce_r_squared = r2_score(y_test_np[:, 0], y_pred_linear_cci[:, 0])
cci_pcedg_r_squared = r2_score(y_test_np[:, 1], y_pred_linear_cci[:, 1])
cci_pces_r_squared = r2_score(y_test_np[:, 2], y_pred_linear_cci[:, 2])
cci_pcef_r_squared = r2_score(y_test_np[:, 3], y_pred_linear_cci[:, 3])
cci_pce_mae = mean_absolute_error(y_test_np[:, 0], y_pred_linear_cci[:, 0])
cci_pcedg_mae = mean_absolute_error(y_test_np[:, 1], y_pred_linear_cci[:, 1])
cci_pces_mae = mean_absolute_error(y_test_np[:, 2], y_pred_linear_cci[:, 2])
cci_pcef_mae = mean_absolute_error(y_test_np[:, 3], y_pred_linear_cci[:, 3])

C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\micha\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [17]:
#Creating dataframe consisting of the predicted values by the linear model for GDP Growth given each true observation of GDP Growth and CCI and exporting it as a csv for later comparison
counter = 0
cci_predictions_true_values = pd.DataFrame(
    {
        'observation':[],
        'PCE_Pred':[],
        'PCEDG_Pred':[],
        'PCES_Pred':[],
        'PCEF_Pred':[],
        'CCI':[]
    }
)

for observation in data['observation']:
    prediction_df = pd.DataFrame([[data['CCI'][counter]]], columns = ['CCI'])
    prediction = model_linear_cci.predict(prediction_df)
    cci_predictions_true_values.loc[len(cci_predictions_true_values)] = [data['observation'][counter],
                                                                                           prediction[0][0],
                                                                                           prediction[0][1],
                                                                                           prediction[0][2],
                                                                                           prediction[0][3],
                                                                                           data['CCI'][counter]]
    counter = counter + 1

cci_predictions_true_values.to_csv(folderpath + 'CCI_Predictions_True_Values.csv')

# Exporting Evaluations for GDP_Growth and CCI Models

In [18]:
#Creating dataframe for evaluation metrics and exporting it as a csv file
linear_models_evaluation_table = pd.DataFrame(
                        {
                        'Economic_Indicator': ['GDP Growth', 'CCI'],
                        'PCE_RMSE': [gdp_growth_pce_rmse, cci_pce_rmse],
                        'PCEDG_RMSE': [gdp_growth_pcedg_rmse, cci_pcedg_rmse],
                        'PCES_RMSE': [gdp_growth_pces_rmse, cci_pces_rmse],
                        'PCEF_RMSE': [gdp_growth_pcef_rmse, cci_pcef_rmse],
                        'PCE_R-Squared': [gdp_growth_pce_r_squared, cci_pce_r_squared],
                        'PCEDG_R-Squared': [gdp_growth_pcedg_r_squared, cci_pcedg_r_squared],
                        'PCES_R-Squared': [gdp_growth_pces_r_squared, cci_pces_r_squared],
                        'PCEF_R-Squared': [gdp_growth_pcef_r_squared, cci_pcef_r_squared],
                        'PCE_MAE': [gdp_growth_pce_mae, cci_pce_mae],
                        'PCEDG_MAE': [gdp_growth_pcedg_mae, cci_pcedg_mae],
                        'PCES_MAE': [gdp_growth_pces_mae, cci_pces_mae],
                        'PCEF_MAE': [gdp_growth_pcef_mae, cci_pcef_mae]
                        }
)

linear_models_evaluation_table.head()

,Economic_Indicator,PCE_RMSE,PCEDG_RMSE,PCES_RMSE,PCEF_RMSE,PCE_R-Squared,PCEDG_R-Squared,PCES_R-Squared,PCEF_R-Squared,PCE_MAE,PCEDG_MAE,PCES_MAE,PCEF_MAE
0,GDP Growth,1147.883295,73.308215,968.292613,44.842100,0.050075,0.002173,0.048034,0.063517,1022.105984,64.437337,875.510593,38.985774
1,CCI,1099.309743,63.838549,934.099821,43.019656,0.128767,0.243313,0.114080,0.138090,937.870038,50.523633,794.444242,35.757239

In [19]:
linear_models_evaluation_table.to_csv(folderpath + 'Economic_Indicator_Evaluation_Table.csv')